/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package totp.demo;

import com.with98labs.otp.TimeBasedOneTimePasswordGenerator;

import javax.crypto.KeyGenerator;
import javax.crypto.spec.SecretKeySpec;
import java.nio.Buffer;
import java.nio.charset.StandardCharsets;
import java.security.InvalidKeyException;
import java.security.Key;
import java.security.NoSuchAlgorithmException;
import java.time.Duration;
import java.time.Instant;

public class App {

    public static void main(String[] args) throws NoSuchAlgorithmException, InvalidKeyException {

        final String secret = "KVKFKRCPNZQUYMLXOVYDSQKJKZDTSRLD";
        final long timeMillis = 1633535465564l;
        final String algorithm = "HmacSHA256";
        final Key key =
                new SecretKeySpec(secret.getBytes(StandardCharsets.US_ASCII), "RAW");

        final TimeBasedOneTimePasswordGenerator totp =
                new TimeBasedOneTimePasswordGenerator(Duration.ofSeconds(30), 6, algorithm);

        final Instant now = Instant.ofEpochMilli(timeMillis);

        System.out.println("secret: "+secret);
        System.out.println("timeMillis: "+timeMillis);
        System.out.println(totp.generateOneTimePasswordString(key, now));

    }

}
